from setuptools import setup, find_packages

setup(
    name="lightgbmlss",
    version="0.4.0",
    description="LightGBMLSS - An extension of LightGBM to probabilistic modelling",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="Alexander März",
    author_email="alex.maerz@gmx.net",
    url="https://github.com/StatMixedML/LightGBMLSS",
    license="Apache License 2.0",
    packages=find_packages(exclude=["docs", "tests*"]),
    include_package_data=True,
    package_data={'': ['datasets/*.csv']},
    zip_safe=True,
    python_requires=">=3.10",
    install_requires=[
        "lightgbm~=4.5.0",
        "torch~=2.4.0",
        "pyro-ppl~=1.9.0",
        "optuna~=4.0.0",
        "properscoring~=0.1",
        "scikit-learn~=1.5.0",
        "numpy~=1.26.0",
        "pandas~=2.2.0",
        "plotnine~=0.13.0",
        "scipy~=1.14.0",
        "shap~=0.46.0",
        "seaborn~=0.13.0",
        "tqdm~=4.66.0",
        "matplotlib~=3.9.0",
        "ipython~=8.26.0",
    ],
    extras_require={
        "docs": ["mkdocs", "mkdocstrings[python]", "mkdocs-jupyter"]
    },
    test_suite="tests",
    tests_require=["flake8", "pytest"],
)
